export type TileID = number & { readonly __brand: "TileID" };
export const tileID = (id: number) => id as TileID;
export type EdgeID = number & { readonly __brand: "EdgeID" };
export const edgeID = (id: number) => id as EdgeID;
export type RoomID = number & { readonly __brand: "RoomID" };
export const roomID = (id: number) => id as RoomID;
export type PlayerID = number & { readonly __brand: "PlayerID" };
export const playerID = (id: number) => id as PlayerID;
export type EntityID = number & { readonly __brand: "EntityID" };
export const entityID = (id: number) => id as EntityID;